"""
==============================================================================
MACROSTRESS-GAN
STOCK MARKET TIMEGAN V2 — VALIDATION
==============================================================================

Purpose:
    Compare real stock-market return/change features against synthetic
    sequences generated by Stock TimeGAN V2.

REAL DATA:
    data/processed/institutions/stock/stock_timegan_features.csv

SYNTHETIC DATA:
    outputs/synthetic/stock/stock_v2_synthetic_sequences.npy

Outputs:
    outputs/validation/stock_v2/

Metrics:
    1. Basic statistics
    2. Pairwise correlation error
    3. Lag-1 temporal correlation
    4. Extreme-event coverage
    5. Distribution KS statistic
    6. Wasserstein distance
    7. Quantile comparison
    8. Range coverage
    9. Overall validation summary

IMPORTANT:
    V1 validation files are NOT modified.
==============================================================================
"""

import os
import sys
import numpy as np
import pandas as pd

from scipy.stats import ks_2samp
from scipy.stats import wasserstein_distance


# =============================================================================
# PROJECT ROOT
# =============================================================================

PROJECT_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.abspath(__file__)
    )
)

if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)


# =============================================================================
# PATHS
# =============================================================================

REAL_DATA_PATH = os.path.join(
    PROJECT_ROOT,
    "data",
    "processed",
    "institutions",
    "stock",
    "stock_timegan_features.csv"
)

SYNTHETIC_DATA_PATH = os.path.join(
    PROJECT_ROOT,
    "outputs",
    "synthetic",
    "stock",
    "stock_v2_synthetic_sequences.npy"
)

OUTPUT_DIR = os.path.join(
    PROJECT_ROOT,
    "outputs",
    "validation",
    "stock_v2"
)


# =============================================================================
# FEATURES
# =============================================================================

FEATURE_NAMES = [
    "NIFTY50_Return",
    "CRUDE_OIL_Return",
    "USD_INR_Return",
    "INDIA_VIX_Change",
    "INDIA_10Y_YIELD_Change"
]


# =============================================================================
# VALIDATION CONFIGURATION
# =============================================================================

LOW_QUANTILE = 0.01
HIGH_QUANTILE = 0.99

QUANTILES = [
    0.01,
    0.05,
    0.25,
    0.50,
    0.75,
    0.95,
    0.99
]


# =============================================================================
# LOAD REAL DATA
# =============================================================================

def load_real_data():

    print()
    print("=" * 78)
    print("LOADING REAL STOCK DATA")
    print("=" * 78)

    print()
    print("Path:")
    print(REAL_DATA_PATH)

    if not os.path.exists(
        REAL_DATA_PATH
    ):

        raise FileNotFoundError(
            f"\nReal feature dataset not found:\n"
            f"{REAL_DATA_PATH}"
        )

    df = pd.read_csv(
        REAL_DATA_PATH
    )

    missing_columns = [
        feature
        for feature in FEATURE_NAMES
        if feature not in df.columns
    ]

    if missing_columns:

        raise ValueError(
            "Missing feature columns:\n"
            + "\n".join(
                missing_columns
            )
        )

    data = df[
        FEATURE_NAMES
    ].astype(
        np.float64
    ).values

    print()
    print(
        f"Rows      : {len(df)}"
    )

    print(
        f"Columns   : {len(FEATURE_NAMES)}"
    )

    print(
        f"Shape     : {data.shape}"
    )

    print(
        f"NaN count : {np.isnan(data).sum()}"
    )

    print(
        f"Inf count : {np.isinf(data).sum()}"
    )

    if np.isnan(data).any():

        raise ValueError(
            "Real dataset contains NaN values."
        )

    if np.isinf(data).any():

        raise ValueError(
            "Real dataset contains Inf values."
        )

    return data


# =============================================================================
# LOAD SYNTHETIC DATA
# =============================================================================

def load_synthetic_data():

    print()
    print("=" * 78)
    print("LOADING STOCK TIMEGAN V2 SYNTHETIC DATA")
    print("=" * 78)

    print()
    print("Path:")
    print(SYNTHETIC_DATA_PATH)

    if not os.path.exists(
        SYNTHETIC_DATA_PATH
    ):

        raise FileNotFoundError(
            f"\nV2 synthetic data not found:\n"
            f"{SYNTHETIC_DATA_PATH}"
        )

    synthetic_sequences = np.load(
        SYNTHETIC_DATA_PATH
    )

    print()
    print(
        f"Shape : {synthetic_sequences.shape}"
    )

    print(
        f"Dtype : {synthetic_sequences.dtype}"
    )

    print(
        f"Min   : {synthetic_sequences.min():.8f}"
    )

    print(
        f"Max   : {synthetic_sequences.max():.8f}"
    )

    if synthetic_sequences.ndim != 3:

        raise ValueError(
            "Synthetic data must have shape "
            "(num_sequences, sequence_length, features)."
        )

    if synthetic_sequences.shape[2] != len(
        FEATURE_NAMES
    ):

        raise ValueError(
            f"Expected {len(FEATURE_NAMES)} features, "
            f"got {synthetic_sequences.shape[2]}."
        )

    if np.isnan(
        synthetic_sequences
    ).any():

        raise ValueError(
            "Synthetic dataset contains NaN values."
        )

    if np.isinf(
        synthetic_sequences
    ).any():

        raise ValueError(
            "Synthetic dataset contains Inf values."
        )

    return synthetic_sequences


# =============================================================================
# FLATTEN SYNTHETIC DATA
# =============================================================================

def flatten_synthetic_data(
    synthetic_sequences
):

    return synthetic_sequences.reshape(
        -1,
        synthetic_sequences.shape[2]
    )


# =============================================================================
# BASIC STATISTICS
# =============================================================================

def calculate_basic_statistics(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("1. BASIC STATISTICS")
    print("=" * 78)

    rows = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_values = real_data[
            :,
            i
        ]

        synthetic_values = synthetic_data[
            :,
            i
        ]

        real_mean = np.mean(
            real_values
        )

        synthetic_mean = np.mean(
            synthetic_values
        )

        real_std = np.std(
            real_values
        )

        synthetic_std = np.std(
            synthetic_values
        )

        real_min = np.min(
            real_values
        )

        synthetic_min = np.min(
            synthetic_values
        )

        real_max = np.max(
            real_values
        )

        synthetic_max = np.max(
            synthetic_values
        )

        mean_abs_difference = abs(
            real_mean
            - synthetic_mean
        )

        std_abs_difference = abs(
            real_std
            - synthetic_std
        )

        rows.append({

            "Feature":
                feature,

            "Real_Mean":
                real_mean,

            "Synthetic_Mean":
                synthetic_mean,

            "Mean_Absolute_Difference":
                mean_abs_difference,

            "Real_Std":
                real_std,

            "Synthetic_Std":
                synthetic_std,

            "Std_Absolute_Difference":
                std_abs_difference,

            "Real_Min":
                real_min,

            "Synthetic_Min":
                synthetic_min,

            "Real_Max":
                real_max,

            "Synthetic_Max":
                synthetic_max
        })

        print()
        print(feature)

        print(
            f"  Real mean       : {real_mean:.8f}"
        )

        print(
            f"  Synthetic mean  : {synthetic_mean:.8f}"
        )

        print(
            f"  Mean difference : {mean_abs_difference:.8f}"
        )

        print(
            f"  Real std        : {real_std:.8f}"
        )

        print(
            f"  Synthetic std   : {synthetic_std:.8f}"
        )

        print(
            f"  Std difference  : {std_abs_difference:.8f}"
        )

    result = pd.DataFrame(
        rows
    )

    return result


# =============================================================================
# CORRELATION MATRIX
# =============================================================================

def calculate_correlation_error(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("2. PAIRWISE CORRELATION")
    print("=" * 78)

    real_corr = np.corrcoef(
        real_data,
        rowvar=False
    )

    synthetic_corr = np.corrcoef(
        synthetic_data,
        rowvar=False
    )

    rows = []

    errors = []

    for i in range(
        len(FEATURE_NAMES)
    ):

        for j in range(
            i + 1,
            len(FEATURE_NAMES)
        ):

            real_value = real_corr[
                i,
                j
            ]

            synthetic_value = synthetic_corr[
                i,
                j
            ]

            error = abs(
                real_value
                - synthetic_value
            )

            errors.append(
                error
            )

            rows.append({

                "Feature_1":
                    FEATURE_NAMES[i],

                "Feature_2":
                    FEATURE_NAMES[j],

                "Real_Correlation":
                    real_value,

                "Synthetic_Correlation":
                    synthetic_value,

                "Absolute_Error":
                    error
            })

            print(
                f"{FEATURE_NAMES[i]:<24} vs "
                f"{FEATURE_NAMES[j]:<28} "
                f"Real={real_value: .4f} "
                f"Synthetic={synthetic_value: .4f} "
                f"Error={error:.4f}"
            )

    mean_error = np.mean(
        errors
    )

    print()
    print(
        f"Mean pairwise correlation error: "
        f"{mean_error:.6f}"
    )

    return (
        pd.DataFrame(rows),
        mean_error
    )


# =============================================================================
# LAG-1 CORRELATION
# =============================================================================

def calculate_lag1(
    sequences
):

    lag_values = []

    for feature_index in range(
        sequences.shape[2]
    ):

        correlations = []

        for sequence in sequences:

            current = sequence[
                :-1,
                feature_index
            ]

            next_values = sequence[
                1:,
                feature_index
            ]

            if (
                np.std(current) == 0
                or np.std(next_values) == 0
            ):

                continue

            correlation = np.corrcoef(
                current,
                next_values
            )[0, 1]

            if np.isfinite(
                correlation
            ):

                correlations.append(
                    correlation
                )

        if correlations:

            lag_values.append(
                np.mean(
                    correlations
                )
            )

        else:

            lag_values.append(
                np.nan
            )

    return np.array(
        lag_values
    )


# =============================================================================
# TEMPORAL VALIDATION
# =============================================================================

def calculate_temporal_validation(
    real_sequences,
    synthetic_sequences
):

    print()
    print("=" * 78)
    print("3. LAG-1 TEMPORAL CORRELATION")
    print("=" * 78)

    real_lag1 = calculate_lag1(
        real_sequences
    )

    synthetic_lag1 = calculate_lag1(
        synthetic_sequences
    )

    rows = []

    differences = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_value = real_lag1[
            i
        ]

        synthetic_value = synthetic_lag1[
            i
        ]

        difference = abs(
            real_value
            - synthetic_value
        )

        differences.append(
            difference
        )

        rows.append({

            "Feature":
                feature,

            "Real_Lag1":
                real_value,

            "Synthetic_Lag1":
                synthetic_value,

            "Absolute_Difference":
                difference
        })

        print()
        print(feature)

        print(
            f"  Real lag-1      : {real_value:.6f}"
        )

        print(
            f"  Synthetic lag-1 : {synthetic_value:.6f}"
        )

        print(
            f"  Difference      : {difference:.6f}"
        )

    mean_difference = np.nanmean(
        differences
    )

    print()
    print(
        f"Mean lag-1 difference: "
        f"{mean_difference:.6f}"
    )

    return (
        pd.DataFrame(rows),
        mean_difference
    )


# =============================================================================
# EXTREME EVENT COVERAGE
# =============================================================================

def calculate_extreme_events(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("4. EXTREME-EVENT COVERAGE")
    print("=" * 78)

    rows = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_values = real_data[
            :,
            i
        ]

        synthetic_values = synthetic_data[
            :,
            i
        ]

        lower_threshold = np.quantile(
            real_values,
            LOW_QUANTILE
        )

        upper_threshold = np.quantile(
            real_values,
            HIGH_QUANTILE
        )

        real_lower = np.sum(
            real_values
            <= lower_threshold
        )

        synthetic_lower = np.sum(
            synthetic_values
            <= lower_threshold
        )

        real_upper = np.sum(
            real_values
            >= upper_threshold
        )

        synthetic_upper = np.sum(
            synthetic_values
            >= upper_threshold
        )

        rows.append({

            "Feature":
                feature,

            "Real_Lower_1pct_Threshold":
                lower_threshold,

            "Real_Upper_99pct_Threshold":
                upper_threshold,

            "Real_Lower_Count":
                real_lower,

            "Synthetic_Lower_Count":
                synthetic_lower,

            "Real_Upper_Count":
                real_upper,

            "Synthetic_Upper_Count":
                synthetic_upper,

            "Lower_Coverage_Ratio":
                (
                    synthetic_lower
                    / real_lower
                    if real_lower > 0
                    else np.nan
                ),

            "Upper_Coverage_Ratio":
                (
                    synthetic_upper
                    / real_upper
                    if real_upper > 0
                    else np.nan
                )
        })

        print()
        print(feature)

        print(
            f"  Lower 1% threshold : "
            f"{lower_threshold:.8f}"
        )

        print(
            f"  Real lower count   : "
            f"{real_lower}"
        )

        print(
            f"  Synth lower count  : "
            f"{synthetic_lower}"
        )

        print(
            f"  Upper 99% threshold: "
            f"{upper_threshold:.8f}"
        )

        print(
            f"  Real upper count   : "
            f"{real_upper}"
        )

        print(
            f"  Synth upper count  : "
            f"{synthetic_upper}"
        )

    return pd.DataFrame(
        rows
    )


# =============================================================================
# DISTRIBUTION TESTS
# =============================================================================

def calculate_distribution_tests(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("5. DISTRIBUTION SIMILARITY")
    print("=" * 78)

    rows = []

    ks_values = []
    wasserstein_values = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_values = real_data[
            :,
            i
        ]

        synthetic_values = synthetic_data[
            :,
            i
        ]

        ks_result = ks_2samp(
            real_values,
            synthetic_values
        )

        ks_statistic = (
            ks_result.statistic
        )

        wasserstein = (
            wasserstein_distance(
                real_values,
                synthetic_values
            )
        )

        ks_values.append(
            ks_statistic
        )

        wasserstein_values.append(
            wasserstein
        )

        rows.append({

            "Feature":
                feature,

            "KS_Statistic":
                ks_statistic,

            "KS_p_value":
                ks_result.pvalue,

            "Wasserstein_Distance":
                wasserstein
        })

        print()
        print(feature)

        print(
            f"  KS statistic       : "
            f"{ks_statistic:.6f}"
        )

        print(
            f"  KS p-value         : "
            f"{ks_result.pvalue:.6e}"
        )

        print(
            f"  Wasserstein        : "
            f"{wasserstein:.6f}"
        )

    mean_ks = np.mean(
        ks_values
    )

    mean_wasserstein = np.mean(
        wasserstein_values
    )

    print()
    print(
        f"Mean KS statistic       : "
        f"{mean_ks:.6f}"
    )

    print(
        f"Mean Wasserstein        : "
        f"{mean_wasserstein:.6f}"
    )

    return (
        pd.DataFrame(rows),
        mean_ks,
        mean_wasserstein
    )


# =============================================================================
# QUANTILE COMPARISON
# =============================================================================

def calculate_quantiles(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("6. QUANTILE COMPARISON")
    print("=" * 78)

    rows = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_values = real_data[
            :,
            i
        ]

        synthetic_values = synthetic_data[
            :,
            i
        ]

        for q in QUANTILES:

            real_q = np.quantile(
                real_values,
                q
            )

            synthetic_q = np.quantile(
                synthetic_values,
                q
            )

            difference = abs(
                real_q
                - synthetic_q
            )

            rows.append({

                "Feature":
                    feature,

                "Quantile":
                    q,

                "Real":
                    real_q,

                "Synthetic":
                    synthetic_q,

                "Absolute_Difference":
                    difference
            })

    result = pd.DataFrame(
        rows
    )

    print(
        result.to_string(
            index=False
        )
    )

    return result


# =============================================================================
# RANGE COVERAGE
# =============================================================================

def calculate_range_coverage(
    real_data,
    synthetic_data
):

    print()
    print("=" * 78)
    print("7. RANGE COVERAGE")
    print("=" * 78)

    rows = []

    for i, feature in enumerate(
        FEATURE_NAMES
    ):

        real_min = np.min(
            real_data[
                :,
                i
            ]
        )

        real_max = np.max(
            real_data[
                :,
                i
            ]
        )

        synthetic_min = np.min(
            synthetic_data[
                :,
                i
            ]
        )

        synthetic_max = np.max(
            synthetic_data[
                :,
                i
            ]
        )

        lower_gap = max(
            0.0,
            real_min - synthetic_min
        )

        upper_gap = max(
            0.0,
            synthetic_max - real_max
        )

        real_range = (
            real_max
            - real_min
        )

        covered_range = (
            min(
                real_max,
                synthetic_max
            )
            -
            max(
                real_min,
                synthetic_min
            )
        )

        if real_range > 0:

            range_coverage_ratio = (
                max(
                    0.0,
                    covered_range
                )
                / real_range
            )

        else:

            range_coverage_ratio = np.nan

        rows.append({

            "Feature":
                feature,

            "Real_Min":
                real_min,

            "Synthetic_Min":
                synthetic_min,

            "Real_Max":
                real_max,

            "Synthetic_Max":
                synthetic_max,

            "Lower_Gap":
                lower_gap,

            "Upper_Gap":
                upper_gap,

            "Range_Coverage_Ratio":
                range_coverage_ratio
        })

        print()
        print(feature)

        print(
            f"  Real range       : "
            f"{real_min:.8f} → {real_max:.8f}"
        )

        print(
            f"  Synthetic range  : "
            f"{synthetic_min:.8f} → {synthetic_max:.8f}"
        )

        print(
            f"  Range coverage   : "
            f"{range_coverage_ratio:.4f}"
        )

    return pd.DataFrame(
        rows
    )


# =============================================================================
# OVERALL SUMMARY
# =============================================================================

def create_summary(
    basic_statistics,
    mean_corr_error,
    mean_lag_error,
    mean_ks,
    mean_wasserstein
):

    mean_abs_feature_mean_difference = (
        basic_statistics[
            "Mean_Absolute_Difference"
        ].mean()
    )

    mean_abs_feature_std_difference = (
        basic_statistics[
            "Std_Absolute_Difference"
        ].mean()
    )

    summary = pd.DataFrame({

        "Metric": [

            "Mean absolute feature mean difference",

            "Mean absolute feature std difference",

            "Mean pairwise correlation error",

            "Mean lag-1 difference",

            "Mean KS statistic",

            "Mean Wasserstein distance"
        ],

        "V2_Value": [

            mean_abs_feature_mean_difference,

            mean_abs_feature_std_difference,

            mean_corr_error,

            mean_lag_error,

            mean_ks,

            mean_wasserstein
        ]
    })

    return summary


# =============================================================================
# SAVE RESULTS
# =============================================================================

def save_results(
    basic_statistics,
    correlation_results,
    extreme_results,
    temporal_results,
    distribution_results,
    quantile_results,
    range_results,
    summary
):

    print()
    print("=" * 78)
    print("SAVING V2 VALIDATION RESULTS")
    print("=" * 78)

    os.makedirs(
        OUTPUT_DIR,
        exist_ok=True
    )

    files = {

        "stock_v2_basic_statistics.csv":
            basic_statistics,

        "stock_v2_correlation.csv":
            correlation_results,

        "stock_v2_extreme_events.csv":
            extreme_results,

        "stock_v2_lag1_comparison.csv":
            temporal_results,

        "stock_v2_distribution_tests.csv":
            distribution_results,

        "stock_v2_quantile_comparison.csv":
            quantile_results,

        "stock_v2_range_coverage.csv":
            range_results,

        "stock_v2_validation_summary.csv":
            summary
    }

    for filename, dataframe in files.items():

        path = os.path.join(
            OUTPUT_DIR,
            filename
        )

        dataframe.to_csv(
            path,
            index=False
        )

        print()
        print(path)


# =============================================================================
# PRINT FINAL SUMMARY
# =============================================================================

def print_final_summary(
    summary
):

    print()
    print("=" * 78)
    print("FINAL V2 VALIDATION SUMMARY")
    print("=" * 78)

    print()

    print(
        summary.to_string(
            index=False
        )
    )

    print()
    print("=" * 78)

    print(
        "Lower values generally indicate closer "
        "agreement for these error/distance metrics."
    )

    print(
        "Validation does NOT by itself establish that "
        "synthetic data are suitable for every downstream use."
    )

    print("=" * 78)


# =============================================================================
# MAIN
# =============================================================================

def main():

    print()
    print("=" * 78)
    print("MACROSTRESS-GAN")
    print("STOCK MARKET TIMEGAN V2 VALIDATION")
    print("=" * 78)

    print()
    print("Project root:")
    print(PROJECT_ROOT)

    print()
    print("Real dataset:")
    print(REAL_DATA_PATH)

    print()
    print("V2 synthetic dataset:")
    print(SYNTHETIC_DATA_PATH)

    print()
    print("Validation output:")
    print(OUTPUT_DIR)

    # =========================================================================
    # LOAD
    # =========================================================================

    real_data = load_real_data()

    synthetic_sequences = load_synthetic_data()

    synthetic_data = flatten_synthetic_data(
        synthetic_sequences
    )

    print()
    print("=" * 78)
    print("DATASET SHAPES")
    print("=" * 78)

    print()
    print(
        f"Real flattened data      : "
        f"{real_data.shape}"
    )

    print(
        f"Synthetic flattened data : "
        f"{synthetic_data.shape}"
    )

    # =========================================================================
    # REAL SEQUENCES
    # =========================================================================
    #
    # The real feature dataset has 4047 observations.
    # The TimeGAN sequence dataset contains 4018 windows of 30 days.
    #
    # We reconstruct the exact real sequence representation used during
    # TimeGAN training by loading the corresponding windows from the
    # processed feature dataset.
    #
    # =========================================================================

    real_sequence_count = (
        len(real_data)
        - 30
        + 1
    )

    if real_sequence_count <= 0:

        raise ValueError(
            "Real dataset is too short to create 30-day sequences."
        )

    real_sequences = np.array([
        real_data[
            i:i + 30
        ]
        for i in range(
            real_sequence_count
        )
    ])

    # =========================================================================
    # VALIDATE EXPECTED REAL SEQUENCE COUNT
    # =========================================================================

    print()
    print(
        f"Real sequence shape      : "
        f"{real_sequences.shape}"
    )

    print(
        f"V2 synthetic shape       : "
        f"{synthetic_sequences.shape}"
    )

    # =========================================================================
    # BASIC STATISTICS
    # =========================================================================

    basic_statistics = calculate_basic_statistics(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # CORRELATION
    # =========================================================================

    (
        correlation_results,
        mean_corr_error
    ) = calculate_correlation_error(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # TEMPORAL
    # =========================================================================

    (
        temporal_results,
        mean_lag_error
    ) = calculate_temporal_validation(
        real_sequences,
        synthetic_sequences
    )

    # =========================================================================
    # EXTREME EVENTS
    # =========================================================================

    extreme_results = calculate_extreme_events(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # DISTRIBUTION
    # =========================================================================

    (
        distribution_results,
        mean_ks,
        mean_wasserstein
    ) = calculate_distribution_tests(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # QUANTILES
    # =========================================================================

    quantile_results = calculate_quantiles(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # RANGE
    # =========================================================================

    range_results = calculate_range_coverage(
        real_data,
        synthetic_data
    )

    # =========================================================================
    # SUMMARY
    # =========================================================================

    summary = create_summary(
        basic_statistics,
        mean_corr_error,
        mean_lag_error,
        mean_ks,
        mean_wasserstein
    )

    # =========================================================================
    # SAVE
    # =========================================================================

    save_results(
        basic_statistics,
        correlation_results,
        extreme_results,
        temporal_results,
        distribution_results,
        quantile_results,
        range_results,
        summary
    )

    # =========================================================================
    # FINAL OUTPUT
    # =========================================================================

    print_final_summary(
        summary
    )

    print()
    print("=" * 78)
    print("STOCK TIMEGAN V2 VALIDATION COMPLETED")
    print("=" * 78)

    print()
    print("Results directory:")
    print(
        OUTPUT_DIR
    )

    print()
    print("V1 validation files were NOT modified.")

    print()
    print("=" * 78)


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    main()