"""
MacroStress-GAN
Portfolio Optimization Agent V2
Stock Market TimeGAN V2

Purpose
-------
Optimize institutional stock-market portfolio weights using the SAME
baseline and stressed TimeGAN paths generated by SimulationAgent.

Important
---------
1. No new synthetic data is generated.
2. No TimeGAN model is loaded here.
3. baseline_raw and stressed_raw are supplied by the orchestrator.
4. Original document weights are preserved exactly.
5. Asset weights are optimized under minimum/maximum constraints.
6. The optimization objective is expected stressed monetary loss.
7. The final reported objective is always recomputed from the FINAL
   optimized weights.
8. Asset "sensitivities" from the institution document are supported.
9. The output structure is compatible with the orchestrator's
   Phase 7, Phase 8, and Phase 9 validation logic.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np


# ============================================================================
# OPTIONAL SCIPY
# ============================================================================

try:
    from scipy.optimize import minimize

    SCIPY_AVAILABLE = True

except Exception:
    minimize = None
    SCIPY_AVAILABLE = False


# ============================================================================
# AGENT
# ============================================================================


class PortfolioOptimizationAgentV2:
    """
    Portfolio Optimization Agent V2.

    Works directly on raw TimeGAN paths.

    Expected TimeGAN feature order:

        0 -> NIFTY50_Return
        1 -> CRUDE_OIL_Return
        2 -> USD_INR_Return
        3 -> INDIA_VIX_Change
        4 -> INDIA_10Y_YIELD_Change

    Asset sensitivities are supplied by the institution configuration.

    Supported sensitivity keys:

        "sensitivities"
        "risk_drivers"
        "risk_driver"
    """

    VERSION = "PortfolioOptimizationAgent-V2"

    FEATURE_NAMES = [
        "NIFTY50_Return",
        "CRUDE_OIL_Return",
        "USD_INR_Return",
        "INDIA_VIX_Change",
        "INDIA_10Y_YIELD_Change",
    ]

    DEFAULT_MIN_WEIGHT = 0.05
    DEFAULT_MAX_WEIGHT = 0.60

    RANDOM_SEED = 42
    RANDOM_CANDIDATES = 5000

    EPS = 1e-12

    # ========================================================================
    # INITIALIZATION
    # ========================================================================

    def __init__(
        self,
        random_seed: int = RANDOM_SEED,
        random_candidates: int = RANDOM_CANDIDATES,
    ):

        self.random_seed = int(random_seed)

        self.random_candidates = int(
            random_candidates
        )

        self.rng = np.random.default_rng(
            self.random_seed
        )

    # ========================================================================
    # GENERIC HELPERS
    # ========================================================================

    @staticmethod
    def _safe_float(
        value: Any,
        default: float = 0.0,
    ) -> float:

        try:

            result = float(value)

            if not np.isfinite(result):

                return float(default)

            return result

        except (
            TypeError,
            ValueError,
        ):

            return float(default)

    @staticmethod
    def _json_safe(value: Any) -> Any:

        if isinstance(value, dict):

            return {
                str(k):
                PortfolioOptimizationAgentV2._json_safe(v)
                for k, v in value.items()
            }

        if isinstance(value, (list, tuple)):

            return [
                PortfolioOptimizationAgentV2._json_safe(v)
                for v in value
            ]

        if isinstance(value, np.ndarray):

            return value.tolist()

        if isinstance(value, np.integer):

            return int(value)

        if isinstance(value, np.floating):

            return float(value)

        if isinstance(value, np.bool_):

            return bool(value)

        if isinstance(value, Path):

            return str(value)

        return value

    # ========================================================================
    # PATH VALIDATION
    # ========================================================================

    @staticmethod
    def _validate_paths(
        baseline_raw: Any,
        stressed_raw: Any,
    ) -> Tuple[np.ndarray, np.ndarray]:

        baseline = np.asarray(
            baseline_raw,
            dtype=np.float64,
        )

        stressed = np.asarray(
            stressed_raw,
            dtype=np.float64,
        )

        if baseline.ndim != 3:

            raise ValueError(
                "baseline_raw must have shape "
                "(scenarios, days, features)."
            )

        if stressed.ndim != 3:

            raise ValueError(
                "stressed_raw must have shape "
                "(scenarios, days, features)."
            )

        if baseline.shape != stressed.shape:

            raise ValueError(
                "baseline_raw and stressed_raw must have "
                "identical shapes."
            )

        if baseline.shape[2] < 5:

            raise ValueError(
                "TimeGAN paths must contain at least 5 features."
            )

        if baseline.shape[0] < 1:

            raise ValueError(
                "TimeGAN paths contain zero scenarios."
            )

        if baseline.shape[1] < 1:

            raise ValueError(
                "TimeGAN paths contain zero days."
            )

        if not np.isfinite(baseline).all():

            raise ValueError(
                "baseline_raw contains non-finite values."
            )

        if not np.isfinite(stressed).all():

            raise ValueError(
                "stressed_raw contains non-finite values."
            )

        return baseline, stressed

    # ========================================================================
    # ASSET EXTRACTION
    # ========================================================================

    @staticmethod
    def _extract_assets(
        institution: Dict[str, Any],
    ) -> Dict[str, Dict[str, Any]]:

        assets = institution.get(
            "portfolio_assets",
            {},
        )

        if not isinstance(
            assets,
            dict,
        ):

            raise ValueError(
                "institution['portfolio_assets'] must be a dictionary."
            )

        if not assets:

            raise ValueError(
                "No portfolio assets were supplied."
            )

        cleaned = {}

        for name, config in assets.items():

            if not isinstance(
                config,
                dict,
            ):

                raise ValueError(
                    f"Portfolio asset '{name}' configuration "
                    "must be a dictionary."
                )

            cleaned[str(name)] = config

        return cleaned

    # ========================================================================
    # ORIGINAL WEIGHTS
    # ========================================================================

    def _extract_original_weights(
        self,
        assets: Dict[str, Dict[str, Any]],
    ) -> Dict[str, float]:

        names = list(
            assets.keys()
        )

        raw_weights = []

        for name in names:

            raw_weight = assets[name].get(
                "weight",
                None,
            )

            if raw_weight is None:

                raise ValueError(
                    f"Original weight missing for asset '{name}'."
                )

            weight = self._safe_float(
                raw_weight,
                default=-1.0,
            )

            if weight < 0.0:

                raise ValueError(
                    f"Invalid original weight for '{name}': "
                    f"{raw_weight}"
                )

            raw_weights.append(
                weight
            )

        raw_weights = np.asarray(
            raw_weights,
            dtype=np.float64,
        )

        total = float(
            np.sum(raw_weights)
        )

        if total <= 0.0:

            raise ValueError(
                "Original portfolio weights sum to zero."
            )

        # Preserve already-valid document weights exactly.
        if np.isclose(
            total,
            1.0,
            atol=1e-10,
        ):

            final_weights = raw_weights.copy()

        else:

            final_weights = (
                raw_weights / total
            )

        return {
            name: float(weight)
            for name, weight in zip(
                names,
                final_weights,
            )
        }

    # ========================================================================
    # CONSTRAINTS
    # ========================================================================

    def _extract_constraints(
        self,
        institution: Dict[str, Any],
    ) -> Tuple[float, float]:

        constraints = institution.get(
            "constraints",
            {},
        )

        if not isinstance(
            constraints,
            dict,
        ):

            constraints = {}

        minimum = self._safe_float(
            constraints.get(
                "min_weight",
                constraints.get(
                    "minimum_weight",
                    self.DEFAULT_MIN_WEIGHT,
                ),
            ),
            self.DEFAULT_MIN_WEIGHT,
        )

        maximum = self._safe_float(
            constraints.get(
                "max_weight",
                constraints.get(
                    "maximum_weight",
                    self.DEFAULT_MAX_WEIGHT,
                ),
            ),
            self.DEFAULT_MAX_WEIGHT,
        )

        if minimum < 0.0:

            raise ValueError(
                "Minimum portfolio weight cannot be negative."
            )

        if maximum > 1.0:

            raise ValueError(
                "Maximum portfolio weight cannot exceed 1.0."
            )

        if minimum > maximum:

            raise ValueError(
                "Minimum portfolio weight cannot exceed maximum."
            )

        return minimum, maximum

    # ========================================================================
    # FEASIBILITY
    # ========================================================================

    @staticmethod
    def _is_feasible(
        weights: np.ndarray,
        minimum: float,
        maximum: float,
        tolerance: float = 1e-8,
    ) -> bool:

        weights = np.asarray(
            weights,
            dtype=np.float64,
        )

        if weights.ndim != 1:

            return False

        if not np.isfinite(weights).all():

            return False

        if not np.isclose(
            np.sum(weights),
            1.0,
            atol=tolerance,
        ):

            return False

        if np.any(
            weights < minimum - tolerance
        ):

            return False

        if np.any(
            weights > maximum + tolerance
        ):

            return False

        return True

    # ========================================================================
    # FEASIBLE PROJECTION
    # ========================================================================

    @staticmethod
    def project_to_feasible(
        weights: Any,
        minimum: float,
        maximum: float,
    ) -> np.ndarray:

        """
        Project arbitrary weights onto:

            sum(weights) = 1
            minimum <= weight <= maximum

        Already-feasible vectors are returned unchanged.
        """

        weights = np.asarray(
            weights,
            dtype=np.float64,
        ).reshape(-1)

        n = len(weights)

        if n == 0:

            raise ValueError(
                "Cannot project an empty weight vector."
            )

        # ---------------------------------------------------------------
        # Preserve already-feasible vectors.
        # ---------------------------------------------------------------

        if PortfolioOptimizationAgentV2._is_feasible(
            weights,
            minimum,
            maximum,
        ):

            return weights.copy()

        # ---------------------------------------------------------------
        # Check feasibility of the constraint system.
        # ---------------------------------------------------------------

        if n * minimum > 1.0 + 1e-12:

            raise ValueError(
                "Portfolio constraints are infeasible: "
                "N * minimum_weight > 1."
            )

        if n * maximum < 1.0 - 1e-12:

            raise ValueError(
                "Portfolio constraints are infeasible: "
                "N * maximum_weight < 1."
            )

        # ---------------------------------------------------------------
        # Start with safe finite values.
        # ---------------------------------------------------------------

        x = np.nan_to_num(
            weights,
            nan=1.0 / n,
            posinf=maximum,
            neginf=minimum,
        )

        x = np.clip(
            x,
            minimum,
            maximum,
        )

        # ---------------------------------------------------------------
        # Redistribute residual.
        # ---------------------------------------------------------------

        for _ in range(1000):

            total = float(
                np.sum(x)
            )

            residual = 1.0 - total

            if abs(residual) <= 1e-12:

                break

            if residual > 0.0:

                room = maximum - x

                active = room > 1e-15

                total_room = float(
                    np.sum(
                        room[active]
                    )
                )

                if total_room <= 1e-15:

                    break

                increment = np.zeros_like(x)

                increment[active] = (
                    residual
                    * room[active]
                    / total_room
                )

                increment = np.minimum(
                    increment,
                    room,
                )

                x += increment

            else:

                room = x - minimum

                active = room > 1e-15

                total_room = float(
                    np.sum(
                        room[active]
                    )
                )

                if total_room <= 1e-15:

                    break

                decrement = np.zeros_like(x)

                decrement[active] = (
                    (-residual)
                    * room[active]
                    / total_room
                )

                decrement = np.minimum(
                    decrement,
                    room,
                )

                x -= decrement

            x = np.clip(
                x,
                minimum,
                maximum,
            )

        # ---------------------------------------------------------------
        # Final numerical correction.
        # ---------------------------------------------------------------

        x = np.clip(
            x,
            minimum,
            maximum,
        )

        residual = (
            1.0
            - float(
                np.sum(x)
            )
        )

        if abs(residual) > 1e-10:

            if residual > 0.0:

                room = maximum - x

                idx = int(
                    np.argmax(room)
                )

                addition = min(
                    residual,
                    room[idx],
                )

                x[idx] += addition

            else:

                room = x - minimum

                idx = int(
                    np.argmax(room)
                )

                subtraction = min(
                    -residual,
                    room[idx],
                )

                x[idx] -= subtraction

        x = np.clip(
            x,
            minimum,
            maximum,
        )

        if not PortfolioOptimizationAgentV2._is_feasible(
            x,
            minimum,
            maximum,
            tolerance=1e-7,
        ):

            raise ValueError(
                "Unable to construct a feasible portfolio weight vector."
            )

        return x

    # ========================================================================
    # RISK DRIVER EXTRACTION
    # ========================================================================

    def _extract_risk_drivers(
        self,
        assets: Dict[str, Dict[str, Any]],
    ) -> Dict[str, Dict[str, float]]:

        """
        Extract asset-level macroeconomic sensitivities.

        Supported input formats:

            "risk_drivers"

            "risk_driver"

            "sensitivities"

        The current Stock Market institution document uses:

            "sensitivities": {
                "NIFTY50": 0.8,
                "USD_INR": -0.1,
                "INDIA_VIX": -0.1
            }

        Internally everything is standardized into risk_drivers.
        """

        drivers = {}

        for asset_name, config in assets.items():

            if not isinstance(
                config,
                dict,
            ):

                drivers[asset_name] = {}

                continue

            # -----------------------------------------------------------
            # First priority: risk_drivers
            # -----------------------------------------------------------

            risk_driver = config.get(
                "risk_drivers",
                None,
            )

            # -----------------------------------------------------------
            # Second priority: risk_driver
            # -----------------------------------------------------------

            if risk_driver is None:

                risk_driver = config.get(
                    "risk_driver",
                    None,
                )

            # -----------------------------------------------------------
            # Third priority: sensitivities
            #
            # THIS IS THE IMPORTANT FIX.
            # -----------------------------------------------------------

            if risk_driver is None:

                risk_driver = config.get(
                    "sensitivities",
                    None,
                )

            # -----------------------------------------------------------
            # Missing drivers.
            # -----------------------------------------------------------

            if not isinstance(
                risk_driver,
                dict,
            ):

                risk_driver = {}

            cleaned = {}

            for variable, coefficient in risk_driver.items():

                coefficient_value = self._safe_float(
                    coefficient,
                    default=0.0,
                )

                cleaned[str(variable)] = (
                    coefficient_value
                )

            drivers[str(asset_name)] = cleaned

        # ---------------------------------------------------------------
        # Fail early instead of silently producing zero-risk portfolios.
        # ---------------------------------------------------------------

        total_driver_count = sum(
            len(driver_map)
            for driver_map in drivers.values()
        )

        if total_driver_count == 0:

            raise ValueError(
                "No portfolio risk drivers/sensitivities were found. "
                "Expected asset configurations to contain "
                "'risk_drivers', 'risk_driver', or 'sensitivities'."
            )

        return drivers

    # ========================================================================
    # FEATURE NAME MAPPING
    # ========================================================================

    @classmethod
    def _feature_index(
        cls,
        name: str,
    ) -> Optional[int]:

        normalized = (
            str(name)
            .strip()
            .upper()
            .replace(" ", "_")
            .replace("-", "_")
        )

        aliases = {

            # -----------------------------------------------------------
            # NIFTY50
            # -----------------------------------------------------------

            "NIFTY50": 0,
            "NIFTY_50": 0,
            "NIFTY50_RETURN": 0,
            "NIFTY_50_RETURN": 0,

            # -----------------------------------------------------------
            # CRUDE OIL
            # -----------------------------------------------------------

            "CRUDE_OIL": 1,
            "CRUDE": 1,
            "CRUDE_OIL_RETURN": 1,

            # -----------------------------------------------------------
            # USD/INR
            # -----------------------------------------------------------

            "USD_INR": 2,
            "USDINR": 2,
            "USD_INR_RETURN": 2,

            # -----------------------------------------------------------
            # INDIA VIX
            # -----------------------------------------------------------

            "INDIA_VIX": 3,
            "VIX": 3,
            "INDIA_VIX_CHANGE": 3,

            # -----------------------------------------------------------
            # INDIA 10-YEAR YIELD
            # -----------------------------------------------------------

            "INDIA_10Y_YIELD": 4,
            "INDIA_10Y": 4,
            "INDIA_10Y_YIELD_CHANGE": 4,
            "10Y_YIELD": 4,
            "INDIA_10_Y_YIELD": 4,
        }

        return aliases.get(
            normalized
        )

    # ========================================================================
    # ASSET RETURN CALCULATION
    # ========================================================================

    def _asset_returns(
        self,
        paths: np.ndarray,
        asset_names: list[str],
        risk_drivers: Dict[str, Dict[str, float]],
    ) -> np.ndarray:

        """
        Convert macro TimeGAN paths into asset return paths.

        Output:

            (scenarios, days, assets)

        Formula:

            Asset Return
                =
                sum(
                    TimeGAN Macro Feature
                    *
                    Asset Sensitivity
                )
        """

        n_scenarios = paths.shape[0]
        n_days = paths.shape[1]
        n_assets = len(asset_names)

        result = np.zeros(
            (
                n_scenarios,
                n_days,
                n_assets,
            ),
            dtype=np.float64,
        )

        for asset_index, asset_name in enumerate(
            asset_names
        ):

            drivers = risk_drivers.get(
                asset_name,
                {},
            )

            if not drivers:

                continue

            for variable, coefficient in drivers.items():

                feature_index = (
                    self._feature_index(
                        variable
                    )
                )

                if feature_index is None:

                    print(
                        f"WARNING: Unknown risk driver "
                        f"'{variable}' for {asset_name}; skipped."
                    )

                    continue

                if feature_index >= paths.shape[2]:

                    print(
                        f"WARNING: Feature index "
                        f"{feature_index} unavailable for "
                        f"{asset_name}; skipped."
                    )

                    continue

                result[
                    :,
                    :,
                    asset_index
                ] += (
                    paths[
                        :,
                        :,
                        feature_index
                    ]
                    * float(coefficient)
                )

        return result

    # ========================================================================
    # PORTFOLIO RETURNS
    # ========================================================================

    @staticmethod
    def _portfolio_returns(
        asset_returns: np.ndarray,
        weights: np.ndarray,
    ) -> np.ndarray:

        return np.einsum(
            "sda,a->sd",
            asset_returns,
            weights,
        )

    # ========================================================================
    # CUMULATIVE RETURNS
    # ========================================================================

    @staticmethod
    def _cumulative_returns(
        daily_returns: np.ndarray,
    ) -> np.ndarray:

        safe_returns = np.asarray(
            daily_returns,
            dtype=np.float64,
        )

        safe_returns = np.clip(
            safe_returns,
            -0.999999,
            None,
        )

        return (
            np.prod(
                1.0 + safe_returns,
                axis=1,
            )
            - 1.0
        )

    # ========================================================================
    # PORTFOLIO METRICS
    # ========================================================================

    def _calculate_metrics(
        self,
        portfolio_returns: np.ndarray,
        portfolio_amount: float,
    ) -> Dict[str, float]:

        cumulative = (
            self._cumulative_returns(
                portfolio_returns
            )
        )

        losses = np.maximum(
            -cumulative,
            0.0,
        )

        if len(losses) == 0:

            raise ValueError(
                "No portfolio scenarios available."
            )

        # ---------------------------------------------------------------
        # VaR 95
        # ---------------------------------------------------------------

        var_95 = float(
            np.quantile(
                losses,
                0.95,
            )
        )

        # ---------------------------------------------------------------
        # Expected Shortfall 95
        # ---------------------------------------------------------------

        tail = losses[
            losses >= var_95
        ]

        if len(tail) == 0:

            expected_shortfall = var_95

        else:

            expected_shortfall = float(
                np.mean(tail)
            )

        # ---------------------------------------------------------------
        # Expected Loss
        # ---------------------------------------------------------------

        expected_loss = float(
            np.mean(losses)
        )

        # ---------------------------------------------------------------
        # Worst Scenario Loss
        # ---------------------------------------------------------------

        worst_loss = float(
            np.max(losses)
        )

        # ---------------------------------------------------------------
        # Maximum Drawdown
        # ---------------------------------------------------------------

        wealth = np.cumprod(
            1.0
            + np.clip(
                portfolio_returns,
                -0.999999,
                None,
            ),
            axis=1,
        )

        running_peak = np.maximum.accumulate(
            wealth,
            axis=1,
        )

        drawdowns = (
            1.0
            - (
                wealth
                / np.maximum(
                    running_peak,
                    self.EPS,
                )
            )
        )

        maximum_drawdown = float(
            np.max(drawdowns)
        )

        # ---------------------------------------------------------------
        # Monetary values
        # ---------------------------------------------------------------

        return {

            "VaR_95":
                var_95,

            "Expected_Shortfall_95":
                expected_shortfall,

            "Maximum_Drawdown":
                maximum_drawdown,

            "Expected_Loss":
                expected_loss,

            "Worst_Scenario_Loss":
                worst_loss,

            "VaR_95_inr":
                var_95 * portfolio_amount,

            "Expected_Shortfall_95_inr":
                expected_shortfall * portfolio_amount,

            "Maximum_Drawdown_inr":
                maximum_drawdown * portfolio_amount,

            "expected_loss_inr":
                expected_loss * portfolio_amount,

            "Worst_Scenario_Loss_inr":
                worst_loss * portfolio_amount,

            "worst_cumulative_return":
                float(
                    np.min(cumulative)
                ),

            "mean_cumulative_return":
                float(
                    np.mean(cumulative)
                ),
        }

    # ========================================================================
    # EVALUATE WEIGHTS
    # ========================================================================

    def _evaluate_weights(
        self,
        weights: np.ndarray,
        baseline_asset_returns: np.ndarray,
        stressed_asset_returns: np.ndarray,
        portfolio_amount: float,
    ) -> Dict[str, Any]:

        weights = np.asarray(
            weights,
            dtype=np.float64,
        )

        baseline_portfolio_returns = (
            self._portfolio_returns(
                baseline_asset_returns,
                weights,
            )
        )

        stressed_portfolio_returns = (
            self._portfolio_returns(
                stressed_asset_returns,
                weights,
            )
        )

        baseline_metrics = (
            self._calculate_metrics(
                baseline_portfolio_returns,
                portfolio_amount,
            )
        )

        stressed_metrics = (
            self._calculate_metrics(
                stressed_portfolio_returns,
                portfolio_amount,
            )
        )

        objective = float(
            stressed_metrics[
                "expected_loss_inr"
            ]
        )

        return {

            "weights":
                weights.copy(),

            "baseline_metrics":
                baseline_metrics,

            "stressed_metrics":
                stressed_metrics,

            "objective_expected_stressed_loss_inr":
                objective,
        }

    # ========================================================================
    # RANDOM FEASIBLE CANDIDATES
    # ========================================================================

    def _generate_random_feasible_candidates(
        self,
        n_assets: int,
        minimum: float,
        maximum: float,
    ) -> np.ndarray:

        candidates = []

        # ---------------------------------------------------------------
        # Equal weights
        # ---------------------------------------------------------------

        equal = np.ones(
            n_assets,
            dtype=np.float64,
        ) / n_assets

        if self._is_feasible(
            equal,
            minimum,
            maximum,
        ):

            candidates.append(
                equal.copy()
            )

        # ---------------------------------------------------------------
        # Minimum + redistribution candidate
        # ---------------------------------------------------------------

        base = np.ones(
            n_assets,
            dtype=np.float64,
        ) * minimum

        remaining = (
            1.0
            - float(
                np.sum(base)
            )
        )

        if remaining >= -1e-12:

            room = np.ones(
                n_assets,
                dtype=np.float64,
            ) * (
                maximum
                - minimum
            )

            room_sum = float(
                np.sum(room)
            )

            if room_sum > 0.0:

                candidate = (
                    base
                    + (
                        remaining
                        * room
                        / room_sum
                    )
                )

                candidate = self.project_to_feasible(
                    candidate,
                    minimum,
                    maximum,
                )

                candidates.append(
                    candidate
                )

        # ---------------------------------------------------------------
        # Random Dirichlet candidates
        # ---------------------------------------------------------------

        attempts = 0

        max_attempts = max(
            self.random_candidates * 10,
            1000,
        )

        while (
            len(candidates)
            < self.random_candidates
            and attempts
            < max_attempts
        ):

            attempts += 1

            candidate = self.rng.dirichlet(
                np.ones(n_assets)
            )

            candidate = self.project_to_feasible(
                candidate,
                minimum,
                maximum,
            )

            if self._is_feasible(
                candidate,
                minimum,
                maximum,
            ):

                candidates.append(
                    candidate
                )

        if not candidates:

            raise RuntimeError(
                "Unable to generate feasible portfolio candidates."
            )

        return np.asarray(
            candidates,
            dtype=np.float64,
        )

    # ========================================================================
    # SLSQP REFINEMENT
    # ========================================================================

    def _run_slsqp(
        self,
        initial_weights: np.ndarray,
        minimum: float,
        maximum: float,
        objective_function,
    ) -> Tuple[np.ndarray, Dict[str, Any]]:

        initial_weights = self.project_to_feasible(
            initial_weights,
            minimum,
            maximum,
        )

        if not SCIPY_AVAILABLE:

            return (
                initial_weights.copy(),
                {
                    "available": False,
                    "success": False,
                    "message":
                        "SciPy unavailable; random candidate retained.",
                    "iterations": 0,
                },
            )

        constraints = [
            {
                "type": "eq",
                "fun": lambda x:
                    float(
                        np.sum(x)
                    ) - 1.0,
            }
        ]

        bounds = [
            (
                minimum,
                maximum,
            )
            for _ in range(
                len(initial_weights)
            )
        ]

        try:

            result = minimize(
                objective_function,
                initial_weights,
                method="SLSQP",
                bounds=bounds,
                constraints=constraints,
                options={
                    "maxiter": 500,
                    "ftol": 1e-12,
                    "disp": False,
                },
            )

            candidate = np.asarray(
                result.x,
                dtype=np.float64,
            )

            if not self._is_feasible(
                candidate,
                minimum,
                maximum,
                tolerance=1e-7,
            ):

                candidate = self.project_to_feasible(
                    candidate,
                    minimum,
                    maximum,
                )

            return (
                candidate,
                {
                    "available": True,

                    "success":
                        bool(
                            result.success
                        ),

                    "message":
                        str(
                            result.message
                        ),

                    "iterations":
                        int(
                            getattr(
                                result,
                                "nit",
                                0,
                            )
                        ),

                    "objective":
                        float(
                            result.fun
                        )
                        if np.isfinite(
                            result.fun
                        )
                        else None,
                },
            )

        except Exception as exc:

            return (
                initial_weights.copy(),
                {
                    "available": True,
                    "success": False,
                    "message":
                        f"SLSQP exception: {exc}",
                    "iterations": 0,
                },
            )

    # ========================================================================
    # WEIGHTS DICTIONARY
    # ========================================================================

    @staticmethod
    def _weights_dict(
        names: list[str],
        weights: np.ndarray,
    ) -> Dict[str, float]:

        return {
            name: float(weight)
            for name, weight in zip(
                names,
                weights,
            )
        }

    # ========================================================================
    # MAIN OPTIMIZATION
    # ========================================================================

    def optimize(
        self,
        institution: Dict[str, Any],
        baseline_raw: Any,
        stressed_raw: Any,
        save_output: bool = True,
    ) -> Dict[str, Any]:

        """
        Exact interface expected by the orchestrator:

            optimize(
                institution=institution,
                baseline_raw=...,
                stressed_raw=...,
                save_output=True,
            )
        """

        # ====================================================================
        # VALIDATE INPUT
        # ====================================================================

        if not isinstance(
            institution,
            dict,
        ):

            raise ValueError(
                "institution must be a dictionary."
            )

        baseline_paths, stressed_paths = (
            self._validate_paths(
                baseline_raw,
                stressed_raw,
            )
        )

        # ====================================================================
        # INSTITUTION
        # ====================================================================

        institution_type = str(
            institution.get(
                "type",
                "Stock Market",
            )
        )

        portfolio_amount = self._safe_float(
            institution.get(
                "portfolio_amount",
                0.0,
            ),
            0.0,
        )

        currency = str(
            institution.get(
                "currency",
                "INR",
            )
        )

        if portfolio_amount <= 0.0:

            raise ValueError(
                "Portfolio amount must be greater than zero."
            )

        # ====================================================================
        # ASSETS
        # ====================================================================

        assets = self._extract_assets(
            institution
        )

        asset_names = list(
            assets.keys()
        )

        n_assets = len(
            asset_names
        )

        # ====================================================================
        # ORIGINAL WEIGHTS
        # ====================================================================

        original_weights_dict = (
            self._extract_original_weights(
                assets
            )
        )

        original_weights = np.asarray(
            [
                original_weights_dict[name]
                for name in asset_names
            ],
            dtype=np.float64,
        )

        # ====================================================================
        # CONSTRAINTS
        # ====================================================================

        minimum_weight, maximum_weight = (
            self._extract_constraints(
                institution
            )
        )

        # ====================================================================
        # RISK DRIVERS
        # ====================================================================

        risk_drivers = (
            self._extract_risk_drivers(
                assets
            )
        )

        # ====================================================================
        # DIAGNOSTIC
        # ====================================================================

        print(
            "\n"
            + "-" * 80
        )

        print(
            "Optimizer risk drivers:"
        )

        for asset_name in asset_names:

            print(
                f"  {asset_name}: "
                f"{risk_drivers.get(asset_name, {})}"
            )

        print(
            "-" * 80
        )

        # ====================================================================
        # VALIDATE RISK DRIVER MAPPING
        # ====================================================================

        mapped_driver_count = 0

        for asset_name in asset_names:

            for variable in risk_drivers.get(
                asset_name,
                {},
            ):

                if self._feature_index(
                    variable
                ) is not None:

                    mapped_driver_count += 1

        if mapped_driver_count == 0:

            raise ValueError(
                "Portfolio sensitivities were found, but none could "
                "be mapped to the five TimeGAN features: "
                f"{self.FEATURE_NAMES}"
            )

        # ====================================================================
        # ORIGINAL WEIGHT FEASIBILITY
        # ====================================================================

        original_weights_feasible = (
            self._is_feasible(
                original_weights,
                minimum_weight,
                maximum_weight,
            )
        )

        if not original_weights_feasible:

            raise ValueError(
                "Original institution portfolio weights are not "
                "feasible under the supplied constraints."
            )

        # ====================================================================
        # TIMEGAN PATH DIFFERENCE
        # ====================================================================

        path_difference = np.abs(
            stressed_paths
            - baseline_paths
        )

        changed_values = int(
            np.count_nonzero(
                path_difference > 1e-12
            )
        )

        scenario_paths_differ = (
            changed_values > 0
        )

        if not scenario_paths_differ:

            raise ValueError(
                "Baseline and stressed TimeGAN paths are identical. "
                "Portfolio optimization requires propagated stressed paths."
            )

        # ====================================================================
        # ASSET RETURNS
        # ====================================================================

        baseline_asset_returns = (
            self._asset_returns(
                baseline_paths,
                asset_names,
                risk_drivers,
            )
        )

        stressed_asset_returns = (
            self._asset_returns(
                stressed_paths,
                asset_names,
                risk_drivers,
            )
        )

        # ====================================================================
        # VERIFY ASSET RETURNS ARE NOT ZERO
        # ====================================================================

        baseline_return_magnitude = float(
            np.sum(
                np.abs(
                    baseline_asset_returns
                )
            )
        )

        stressed_return_magnitude = float(
            np.sum(
                np.abs(
                    stressed_asset_returns
                )
            )
        )

        if (
            baseline_return_magnitude <= self.EPS
            and
            stressed_return_magnitude <= self.EPS
        ):

            raise ValueError(
                "Asset return paths are all zero. "
                "Check portfolio sensitivities and TimeGAN "
                "feature mapping."
            )

        # ====================================================================
        # ORIGINAL PORTFOLIO
        # ====================================================================

        baseline_evaluation = (
            self._evaluate_weights(
                original_weights,
                baseline_asset_returns,
                stressed_asset_returns,
                portfolio_amount,
            )
        )

        baseline_objective = float(
            baseline_evaluation[
                "objective_expected_stressed_loss_inr"
            ]
        )

        # ====================================================================
        # RANDOM CANDIDATES
        # ====================================================================

        candidates = (
            self._generate_random_feasible_candidates(
                n_assets,
                minimum_weight,
                maximum_weight,
            )
        )

        candidate_records = []

        candidate_evaluations = []

        for index, candidate in enumerate(
            candidates
        ):

            evaluation = (
                self._evaluate_weights(
                    candidate,
                    baseline_asset_returns,
                    stressed_asset_returns,
                    portfolio_amount,
                )
            )

            objective_value = float(
                evaluation[
                    "objective_expected_stressed_loss_inr"
                ]
            )

            candidate_evaluations.append(
                (
                    candidate.copy(),
                    objective_value,
                )
            )

            candidate_records.append(
                {
                    "name":
                        f"random_{index}",

                    "weights":
                        self._weights_dict(
                            asset_names,
                            candidate,
                        ),

                    "expected_stressed_loss_inr":
                        objective_value,
                }
            )

        # ====================================================================
        # BEST RANDOM CANDIDATE
        # ====================================================================

        best_random_index = int(
            np.argmin(
                [
                    value
                    for _, value
                    in candidate_evaluations
                ]
            )
        )

        best_random_weights = (
            candidate_evaluations[
                best_random_index
            ][0].copy()
        )

        best_random_objective = float(
            candidate_evaluations[
                best_random_index
            ][1]
        )

        best_random_name = (
            candidate_records[
                best_random_index
            ]["name"]
        )

        # ====================================================================
        # SORT FOR REPORTING
        # ====================================================================

        candidate_records.sort(
            key=lambda item:
                item[
                    "expected_stressed_loss_inr"
                ]
        )

        # ====================================================================
        # SLSQP OBJECTIVE
        # ====================================================================

        def objective(weights):

            weights = np.asarray(
                weights,
                dtype=np.float64,
            )

            # ---------------------------------------------------------------
            # SLSQP can temporarily evaluate an infeasible point.
            # Return a large penalty rather than crashing.
            # ---------------------------------------------------------------

            if not self._is_feasible(
                weights,
                minimum_weight,
                maximum_weight,
                tolerance=1e-5,
            ):

                return 1e30

            evaluation = (
                self._evaluate_weights(
                    weights,
                    baseline_asset_returns,
                    stressed_asset_returns,
                    portfolio_amount,
                )
            )

            return float(
                evaluation[
                    "objective_expected_stressed_loss_inr"
                ]
            )

        # ====================================================================
        # SLSQP
        # ====================================================================

        refined_weights, slsqp_info = (
            self._run_slsqp(
                best_random_weights,
                minimum_weight,
                maximum_weight,
                objective,
            )
        )

        # ====================================================================
        # FINAL FEASIBILITY
        # ====================================================================

        refined_weights = (
            self.project_to_feasible(
                refined_weights,
                minimum_weight,
                maximum_weight,
            )
        )

        # ====================================================================
        # FINAL SLSQP EVALUATION
        # ====================================================================

        slsqp_evaluation = (
            self._evaluate_weights(
                refined_weights,
                baseline_asset_returns,
                stressed_asset_returns,
                portfolio_amount,
            )
        )

        slsqp_objective = float(
            slsqp_evaluation[
                "objective_expected_stressed_loss_inr"
            ]
        )

        # ====================================================================
        # SELECT BEST ACTUAL EVALUATED SOLUTION
        # ====================================================================

        if (
            best_random_objective
            < slsqp_objective
        ):

            refined_weights = (
                best_random_weights.copy()
            )

            final_evaluation = (
                self._evaluate_weights(
                    refined_weights,
                    baseline_asset_returns,
                    stressed_asset_returns,
                    portfolio_amount,
                )
            )

            optimized_objective = float(
                final_evaluation[
                    "objective_expected_stressed_loss_inr"
                ]
            )

            selected_candidate = (
                best_random_name
            )

            selected_method = (
                "random_search"
            )

        else:

            final_evaluation = (
                slsqp_evaluation
            )

            optimized_objective = (
                slsqp_objective
            )

            selected_candidate = (
                "slsqp_refined"
            )

            selected_method = (
                "slsqp"
            )

        # ====================================================================
        # FINAL FEASIBILITY
        # ====================================================================

        optimized_weights_valid = (
            self._is_feasible(
                refined_weights,
                minimum_weight,
                maximum_weight,
                tolerance=1e-7,
            )
        )

        if not optimized_weights_valid:

            raise RuntimeError(
                "Final optimized weights are not feasible."
            )

        # ====================================================================
        # FINAL OBJECTIVE CONSISTENCY
        # ====================================================================

        consistency_evaluation = (
            self._evaluate_weights(
                refined_weights,
                baseline_asset_returns,
                stressed_asset_returns,
                portfolio_amount,
            )
        )

        consistency_objective = float(
            consistency_evaluation[
                "objective_expected_stressed_loss_inr"
            ]
        )

        objective_consistent = bool(
            np.isclose(
                optimized_objective,
                consistency_objective,
                rtol=1e-10,
                atol=1e-6,
            )
        )

        if not objective_consistent:

            raise RuntimeError(
                "Portfolio optimization objective consistency check failed."
            )

        # ====================================================================
        # FINAL REDUCTION
        # ====================================================================

        loss_reduction = (
            baseline_objective
            - optimized_objective
        )

        if abs(
            baseline_objective
        ) > 1e-12:

            loss_reduction_percent = (
                loss_reduction
                / baseline_objective
            ) * 100.0

        else:

            loss_reduction_percent = 0.0

        improvement_verified = bool(
            optimized_objective
            < baseline_objective
            - 1e-9
        )

        # ====================================================================
        # BASELINE PORTFOLIO
        # ====================================================================

        baseline_portfolio = {

            "weights":
                original_weights_dict,

            "weight_sum":
                float(
                    np.sum(
                        original_weights
                    )
                ),

            "weights_valid":
                original_weights_feasible,

            "baseline_metrics":
                baseline_evaluation[
                    "baseline_metrics"
                ],

            "stressed_metrics":
                baseline_evaluation[
                    "stressed_metrics"
                ],
        }

        # ====================================================================
        # OPTIMIZED PORTFOLIO
        # ====================================================================

        optimized_weights_dict = (
            self._weights_dict(
                asset_names,
                refined_weights,
            )
        )

        optimized_portfolio = {

            "weights":
                optimized_weights_dict,

            "weight_sum":
                float(
                    np.sum(
                        refined_weights
                    )
                ),

            "weights_valid":
                optimized_weights_valid,

            "baseline_metrics":
                final_evaluation[
                    "baseline_metrics"
                ],

            "stressed_metrics":
                final_evaluation[
                    "stressed_metrics"
                ],

            "objective_expected_stressed_loss_inr":
                optimized_objective,
        }

        # ====================================================================
        # TOP CANDIDATES
        # ====================================================================

        candidate_summary = []

        for record in candidate_records[:10]:

            candidate_summary.append(
                {
                    "name":
                        record[
                            "name"
                        ],

                    "weights":
                        record[
                            "weights"
                        ],

                    "expected_stressed_loss_inr":
                        record[
                            "expected_stressed_loss_inr"
                        ],
                }
            )

        # ====================================================================
        # OPTIMIZATION RESULT
        # ====================================================================

        optimization_result = {

            "candidate_count":
                int(
                    len(
                        candidate_records
                    )
                ),

            "selected_candidate":
                selected_candidate,

            "selected_method":
                selected_method,

            "baseline_expected_stressed_loss_inr":
                baseline_objective,

            "optimized_expected_stressed_loss_inr":
                optimized_objective,

            "loss_reduction_inr":
                loss_reduction,

            "loss_reduction_percent":
                loss_reduction_percent,

            "improvement_verified":
                improvement_verified,

            "objective_consistent":
                objective_consistent,
        }

        # ====================================================================
        # OPTIMIZER METADATA
        # ====================================================================

        optimizer_metadata = {

            "name":
                self.VERSION,

            "version":
                self.VERSION,

            "objective":
                "minimize_expected_stressed_monetary_loss",

            "objective_definition":
                "Expected loss across stressed TimeGAN portfolio scenarios",

            "same_timegan_paths_reused":
                True,

            "new_synthetic_data_generated_during_optimization":
                False,

            "baseline_path_shape":
                list(
                    baseline_paths.shape
                ),

            "stressed_path_shape":
                list(
                    stressed_paths.shape
                ),

            "scenario_paths_differ":
                scenario_paths_differ,

            "changed_timegan_values":
                changed_values,

            "random_seed":
                self.random_seed,

            "random_candidates":
                self.random_candidates,

            "scipy_available":
                SCIPY_AVAILABLE,

            "slsqp_success":
                bool(
                    slsqp_info.get(
                        "success",
                        False,
                    )
                ),

            "slsqp_message":
                slsqp_info.get(
                    "message"
                ),

            "slsqp_iterations":
                slsqp_info.get(
                    "iterations",
                    0,
                ),

            "baseline_asset_return_abs_sum":
                baseline_return_magnitude,

            "stressed_asset_return_abs_sum":
                stressed_return_magnitude,
        }

        # ====================================================================
        # CONSTRAINT METADATA
        # ====================================================================

        constraints_output = {

            "minimum_weight":
                minimum_weight,

            "maximum_weight":
                maximum_weight,

            "sum_weights_required":
                1.0,

            "original_weights_valid":
                original_weights_feasible,

            "optimized_weights_valid":
                optimized_weights_valid,

            "optimized_weight_sum":
                float(
                    np.sum(
                        refined_weights
                    )
                ),
        }

        # ====================================================================
        # INSTITUTION OUTPUT
        # ====================================================================

        institution_output = {

            "type":
                institution_type,

            "portfolio_amount":
                portfolio_amount,

            "currency":
                currency,
        }

        # ====================================================================
        # COMPLETE RESULT
        # ====================================================================

        result = {

            "status":
                "success",

            "optimizer":
                optimizer_metadata,

            "institution":
                institution_output,

            "constraints":
                constraints_output,

            "portfolio_assets":
                assets,

            "risk_drivers":
                risk_drivers,

            "original_weights":
                original_weights_dict,

            "baseline_portfolio":
                baseline_portfolio,

            "optimized_portfolio":
                optimized_portfolio,

            "optimization_result":
                optimization_result,

            "candidate_summary":
                candidate_summary,

            "validation": {

                "objective_consistent":
                    objective_consistent,

                "optimized_weights_valid":
                    optimized_weights_valid,

                "improvement_verified":
                    improvement_verified,

                "same_timegan_paths_reused":
                    True,

                "new_synthetic_data_generated":
                    False,
            },

            "timegan_input": {

                "baseline_shape":
                    list(
                        baseline_paths.shape
                    ),

                "stressed_shape":
                    list(
                        stressed_paths.shape
                    ),

                "same_paths_reused":
                    True,

                "new_synthetic_data_generated":
                    False,
            },
        }

        # ====================================================================
        # SAVE OUTPUT
        # ====================================================================

        if save_output:

            project_root = Path(
                institution.get(
                    "project_root",
                    Path(__file__).resolve().parents[1],
                )
            )

            output_dir = (
                project_root
                / "outputs"
            )

            output_dir.mkdir(
                parents=True,
                exist_ok=True,
            )

            output_path = (
                output_dir
                / "stock_portfolio_optimization_v2.json"
            )

            with open(
                output_path,
                "w",
                encoding="utf-8",
            ) as f:

                json.dump(
                    self._json_safe(result),
                    f,
                    indent=2,
                    ensure_ascii=False,
                )

            result[
                "output_path"
            ] = str(
                output_path
            )

        # ====================================================================
        # CONSOLE SUMMARY
        # ====================================================================

        print(
            "\n"
            + "=" * 80
        )

        print(
            "PORTFOLIO OPTIMIZATION V2"
        )

        print(
            "=" * 80
        )

        print(
            f"Assets                       : "
            f"{n_assets}"
        )

        print(
            f"Portfolio amount             : "
            f"{currency} {portfolio_amount:,.2f}"
        )

        print(
            f"Minimum weight               : "
            f"{minimum_weight:.4f}"
        )

        print(
            f"Maximum weight               : "
            f"{maximum_weight:.4f}"
        )

        print(
            f"Original weights             : "
            f"{original_weights_dict}"
        )

        print(
            f"Optimized weights            : "
            f"{optimized_weights_dict}"
        )

        print(
            f"Baseline stressed loss       : "
            f"{currency} {baseline_objective:,.2f}"
        )

        print(
            f"Optimized stressed loss      : "
            f"{currency} {optimized_objective:,.2f}"
        )

        print(
            f"Loss reduction               : "
            f"{currency} {loss_reduction:,.2f}"
        )

        print(
            f"Loss reduction (%)           : "
            f"{loss_reduction_percent:.2f}%"
        )

        print(
            f"Improvement verified         : "
            f"{improvement_verified}"
        )

        print(
            f"Objective consistent         : "
            f"{objective_consistent}"
        )

        print(
            f"Same TimeGAN paths reused    : "
            f"True"
        )

        print(
            f"New synthetic data generated: "
            f"False"
        )

        print(
            f"SLSQP success                : "
            f"{slsqp_info.get('success', False)}"
        )

        print(
            "=" * 80
        )

        return result


# ============================================================================
# BACKWARD-COMPATIBLE CLASS NAME
# ============================================================================

PortfolioOptimizationAgent = (
    PortfolioOptimizationAgentV2
)


# ============================================================================
# DIRECT IMPORT TEST
# ============================================================================

if __name__ == "__main__":

    print(
        "PortfolioOptimizationAgent-V2"
    )

    print(
        "Import test:"
    )

    print(
        f"  Class: "
        f"{PortfolioOptimizationAgent.__name__}"
    )

    print(
        f"  Version: "
        f"{PortfolioOptimizationAgentV2.VERSION}"
    )

    print(
        f"  SciPy available: "
        f"{SCIPY_AVAILABLE}"
    )